### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by hackguy25** [JuliaImages/www.juliaimages.org#36]
I noticed the site `http://juliaimages.github.io/latest` cannot be accessed.
![image](https://user-images.githubusercontent.com/20540694/50296103-f33e2180-0479-11e9-9949-494495f22ec7.png)
Is it being migrated or is there an error?

**Comment by zygmuntszpak** [comment]
It's in the process of being migrated and I think something went wrong along the way. The current documentation can be [found here](https://juliaimages.org/latest/): `https://juliaimages.org/latest/`

**Comment by zygmuntszpak** [comment]
@timholy Perhaps you could change the link that appears prominently in `https://github.com/JuliaImages` which currently says `http://juliaimages.github.io/latest`  to `https://juliaimages.org/latest/`

**Comment by ViralBShah** [comment]
That's right, the old url won't work. I fixed it in a few places I found.

**Comment by ViralBShah** [comment]
Updated it on top. It is best to use `https://juliaimages.org`. You automatically get the `latest`, but using just the site name without any paths will offer more flexibility-  say perhaps when there is a landing page (which is not docs).

**Comment by ViralBShah** [comment]
The domain is also verified now on github.

**Comment by timholy** [comment]
I'm still getting a 404

**Comment by ViralBShah** [comment]
That's right - when we transition github pages to our own domain, the older `github.io` domains don't work. We need to point things to: `https://juliaimages.org/latest`.

**Comment by ViralBShah** [comment]
In the same way, testimages now is at: http://testimages.juliaimages.org

**Comment by timholy** [comment]
Naive question, but is there a way we can set up some kind of forwarding? I'm worried about stale links scattered across discourse etc. Over the years I've probably posted ~100 links to the JuliaImages documentation.

**Comment by ViralBShah** [comment]
Let me see if I can make it work. Sorry about that - I guess I should have mentioned that before I started on this.

**Comment by ViralBShah** [comment]
@timholy I renamed this repo to its original name - `juliaimages.github.io`. Turns out that makes the old URLs work as well as the new ones.

**Comment by timholy** [comment]
Working for me now, thanks!

**Comment by ViralBShah** [comment]
I am done with pointing JuliaImages.org to this repo and that part seems working smoothly. So I don't need to have the owner but here any more.

I seem to have created a bit of trouble work the migration and apologize for creating the extra work.

**Comment by Evizero** [comment]
is the `www` prefix supposed to work that is linked at the repo header? (it doesn't for me, but it might be my setup)

**Comment by ViralBShah** [comment]
The `www` has been a lot of trouble to get working. So I have just dropped it. It also seems a bit redundant in todays times.
